name: test

on:
  push:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run test
        run: |
          go build -v .
          go test -v .

      - name: Run generate test
        run: |
          go test -v .
        working-directory: ./gen
